-- =========================================================
-- SUPPORT TICKETS
-- =========================================================

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'open'
    check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text null,
  file_url text null,
  file_name text null,
  file_type text null,
  read_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint support_message_has_content
    check (
      nullif(trim(coalesce(body, '')), '') is not null
      or file_url is not null
    )
);

create index if not exists support_tickets_user_id_idx
on public.support_tickets(user_id, updated_at desc);

create index if not exists support_messages_ticket_idx
on public.support_messages(ticket_id, created_at asc);

-- =========================================================
-- SECURITY HELPERS
-- =========================================================

create or replace function public.can_access_support_ticket(
  _ticket_id uuid
)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.support_tickets t
    where t.id = _ticket_id
      and (
        t.user_id = auth.uid()
        or public.has_role('admin', auth.uid())
      )
  );
$$;

-- =========================================================
-- RLS
-- =========================================================

alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;

drop policy if exists "support tickets read"
on public.support_tickets;

create policy "support tickets read"
on public.support_tickets
for select
to authenticated
using (
  user_id = auth.uid()
  or public.has_role('admin', auth.uid())
);

drop policy if exists "support tickets create"
on public.support_tickets;

create policy "support tickets create"
on public.support_tickets
for insert
to authenticated
with check (
  user_id = auth.uid()
);

drop policy if exists "support tickets update"
on public.support_tickets;

create policy "support tickets update"
on public.support_tickets
for update
to authenticated
using (
  user_id = auth.uid()
  or public.has_role('admin', auth.uid())
)
with check (
  user_id = auth.uid()
  or public.has_role('admin', auth.uid())
);

drop policy if exists "support messages read"
on public.support_messages;

create policy "support messages read"
on public.support_messages
for select
to authenticated
using (
  public.can_access_support_ticket(ticket_id)
);

drop policy if exists "support messages create"
on public.support_messages;

create policy "support messages create"
on public.support_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and public.can_access_support_ticket(ticket_id)
);

drop policy if exists "support messages update read"
on public.support_messages;

create policy "support messages update read"
on public.support_messages
for update
to authenticated
using (
  public.can_access_support_ticket(ticket_id)
)
with check (
  public.can_access_support_ticket(ticket_id)
);

-- =========================================================
-- KEEP TICKET UPDATED
-- =========================================================

create or replace function public.touch_support_ticket()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.support_tickets
  set updated_at = now()
  where id = new.ticket_id;

  return new;
end;
$$;

drop trigger if exists trg_touch_support_ticket
on public.support_messages;

create trigger trg_touch_support_ticket
after insert on public.support_messages
for each row
execute function public.touch_support_ticket();

-- =========================================================
-- ADMIN + USER NOTIFICATIONS
-- =========================================================

create or replace function public.notify_support_ticket_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (
    user_id,
    title,
    body,
    type,
    link,
    is_read
  )
  select
    ur.user_id,
    'تذكرة دعم جديدة #' || new.ticket_number,
    'تم فتح تذكرة دعم جديدة',
    'support_ticket',
    '/admin?tab=support',
    false
  from public.user_roles ur
  where ur.role = 'admin';

  return new;
end;
$$;

drop trigger if exists trg_notify_support_ticket_created
on public.support_tickets;

create trigger trg_notify_support_ticket_created
after insert on public.support_tickets
for each row
execute function public.notify_support_ticket_created();


create or replace function public.notify_support_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ticket public.support_tickets%rowtype;
  v_preview text;
  v_previous_count integer;
  v_is_admin boolean;
  v_link text;
begin
  select *
  into v_ticket
  from public.support_tickets
  where id = new.ticket_id;

  if not found then
    return new;
  end if;

  v_is_admin := public.has_role('admin', new.sender_id);

  v_preview :=
    case
      when nullif(trim(coalesce(new.body, '')), '') is not null
        then left(trim(new.body), 120)
      when new.file_url is not null
        then '📎 أرسل ملفًا'
      else
        'رسالة جديدة'
    end;

  /*
    عدد الرسائل بعد إدخال الرسالة الحالية.
    الرسالة الأولى لا نرسل لها إشعارًا ثانيًا للأدمن،
    لأن إنشاء التذكرة نفسه أرسل إشعار "تذكرة جديدة".
  */
  select count(*)
  into v_previous_count
  from public.support_messages
  where ticket_id = new.ticket_id;

  if v_is_admin then

    if exists (
      select 1
      from public.user_roles
      where user_id = v_ticket.user_id
        and role = 'office'
    ) then
      v_link := '/office/profile?support=' || v_ticket.id;
    else
      v_link := '/account?support=' || v_ticket.id;
    end if;

    insert into public.notifications (
      user_id,
      title,
      body,
      type,
      link,
      is_read
    )
    values (
      v_ticket.user_id,
      'تم الرد على تذكرتك #' || v_ticket.ticket_number,
      v_preview,
      'support_ticket',
      v_link,
      false
    );

  elsif v_previous_count > 1 then

    insert into public.notifications (
      user_id,
      title,
      body,
      type,
      link,
      is_read
    )
    select
      ur.user_id,
      'رسالة جديدة في التذكرة #' || v_ticket.ticket_number,
      v_preview,
      'support_ticket',
      '/admin?tab=support',
      false
    from public.user_roles ur
    where ur.role = 'admin';

  end if;

  return new;
end;
$$;

drop trigger if exists trg_notify_support_message
on public.support_messages;

create trigger trg_notify_support_message
after insert on public.support_messages
for each row
execute function public.notify_support_message();

-- =========================================================
-- REALTIME
-- =========================================================

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'support_tickets'
  ) then
    alter publication supabase_realtime
      add table public.support_tickets;
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'support_messages'
  ) then
    alter publication supabase_realtime
      add table public.support_messages;
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifications'
  ) then
    alter publication supabase_realtime
      add table public.notifications;
  end if;
end;
$$;
